default_agent: get_weather_agent_runtime
agents:
  get_weather_agent_runtime:
    name: get_weather_agent_runtime
    entrypoint: get_weather_agent_runtime.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::218208277580:role/service-role/Amazon-Bedrock-IAM-Role-20240102T112809
      account: '218208277580'
      region: us-west-2
      ecr_repository: 218208277580.dkr.ecr.us-west-2.amazonaws.com/bedrockagentrepo
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: get_weather_agent_runtime-45UEqV91hR
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:218208277580:runtime/get_weather_agent_runtime-45UEqV91hR
      agent_session_id: fd4652bd-67c4-4276-9f30-d2a6493e0613
    authorizer_configuration: null
    oauth_configuration: null
